### ISSUE TITLE
内置的参数好像不存在

### ISSUE THREAD

**Issue by york-cmd** [Lotus6/AutoRepeater#1]
<img width="1311" alt="image" src="https://github.com/Lotus6/AutoRepeater/assets/64241747/c4c9d239-762c-47e5-a765-ba065a591696">
<img width="534" alt="image" src="https://github.com/Lotus6/AutoRepeater/assets/64241747/30395c0f-5157-4b33-bcbc-bfbe0a7e5bf8">

**Comment by Lotus6** [comment]
1.8jdk的，高版本我还没打包

**Comment by DatangST** [comment]
有打包好的jar吗

**Comment by Lotus6** [comment]
已修复，打包完发自于月球在 2023年9月4日，22:25，DatangST ***@***.***> 写道：﻿
有打包好的jar吗

**Comment by Lotus6** [comment]
close
